add discovery node

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -65,61 +65,63 @@ jobs:
       - name: Start etcd run tests
         run: |
           version="$(yq .version rockcraft.yaml)"
-          docker network create etcd-net
+
+          discovery_node=$(docker run -d \
+            --name discovery-node \
+            -e ETCD_NAME=discovery-node \
+            -e ETCD_INITIAL_ADVERTISE_PEER_URLS=http://localhost:2380 \
+            -e ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 \
+            -e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 \
+            -e ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379 \
+            charmed-etcd:"${version}"
+          )
+          discovery_ip=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' "${discovery_node}")
+
+          TOKEN="random-token"
+          docker exec "${discovery_node}" etcdctl put /_etcd/registry/${TOKEN}/_config/size 3
 
           MEMBERS=(etcd0 etcd1 etcd2)
-          INITIAL_CLUSTER=""
-          for MEMBER in "${MEMBERS[@]}"; do
-            INITIAL_CLUSTER+="${MEMBER}=http://${MEMBER}:2380,"
+          for NAME in "${MEMBERS[@]}"; do
+            docker run -d \
+              --name "$NAME" \
+              -e ETCD_NAME="${NAME}" \
+              -e ETCD_INITIAL_ADVERTISE_PEER_URLS="http://localhost:2380" \
+              -e ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380" \
+              -e ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379" \
+              -e ETCD_ADVERTISE_CLIENT_URLS="http://localhost:2379" \
+              -e ETCD_DISCOVERY_TOKEN="${TOKEN}" \
+              -e ETCD_DISCOVERY_ENDPOINTS="http://${discovery_ip}:2379" \
+              "${ETCD_IMG}"
           done
-          INITIAL_CLUSTER="${INITIAL_CLUSTER%,}"
 
-          for MEMBER in "${MEMBERS[@]}"; do
-             docker run -d --rm \
-               --name "${MEMBER}" \
-               --network etcd-net \
-               -e ETCD_NAME="${MEMBER}" \
-               -e ETCD_INITIAL_ADVERTISE_PEER_URLS="http://${MEMBER}:2380" \
-               -e ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380" \
-               -e ETCD_ADVERTISE_CLIENT_URLS="http://${MEMBER}:2379" \
-               -e ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379" \
-               -e ETCD_INITIAL_CLUSTER_TOKEN="etcd_cluster" \
-               -e ETCD_INITIAL_CLUSTER="${INITIAL_CLUSTER}" \
-               -e ETCD_INITIAL_CLUSTER_STATE=new \
-               charmed-etcd:"${version}"
-          done
-          
           # wait a bit for it to fully initialize
           sleep 15s
           
-          cluster=$(docker exec etcd0 etcdctl --endpoints=http://localhost:2379 member list)
-          count=$(grep -c ', started,' <<< "$cluster")
-          if [ "$count" -ne 3 ]; then
-            echo "expected 3 members but got $count"
-            exit 1
-          fi
+          cluster=$(docker exec etcd0 etcdctl member list)
+          for expected in "${MEMBERS[@]}"; do
+            if ! grep -q "${expected}" <<< "$cluster"; then
+              echo "member ${expected} not found in cluster:"
+              echo "${cluster}"
+              exit 1
+            fi
+          done
 
-          if ! docker exec etcd0 etcdctl --endpoints=http://localhost:2379 put foo bar; then
+          if ! docker exec etcd0 etcdctl put foo bar; then
             echo "etcd failed put test"
             exit 1
           fi
 
           sleep 2s
 
-          VALUE=$(docker exec etcd1 etcdctl --endpoints=http://localhost:2379 get foo --print-value-only)
+          VALUE=$(docker exec etcd1 etcdctl get foo --print-value-only)
           if [ "$VALUE" != "bar" ]; then
             echo "expected 'bar' but got '$VALUE'"
             exit 1
           fi
 
-          health-check(){
-            local MEMBER="$1"
-            if ! docker exec "${MEMBER}" etcdctl --endpoints=http://localhost:2379 endpoint health | grep -q "is healthy"; then
-              echo "member ${MEMBER} failed health check"
+          for NAME in "${MEMBERS[@]}"; do
+            if ! docker exec "${NAME}" etcdctl endpoint health | grep -q "is healthy"; then
+              echo "member ${NAME} failed health check"
               exit 1
             fi
-          }
-
-          health-check etcd0
-          health-check etcd1
-          health-check etcd2
+          done
